config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'questions#index'

  resources :questions, except: :edit do
    delete :delete_attachment, on: :member
    resources :answers, shallow: true, only: %i[create destroy edit update] do
      patch :choose_best, on: :member
      delete :delete_attachment, on: :member
    end
  end

  resources :attachments, only: %i[destroy]
  resources :links, only: %i[destroy]
  resources :rewards, only: %i[index]
  resources :votes, only: %i[create destroy]
  resources :comments, only: %i[create new]
  resources :subscriptions, only: %i[create destroy]

  namespace 'api' do
    namespace 'v1' do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, shallow: true, only: %i[index show create update destroy]
      end
    end
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include IsVotable
  include IsSubscriptable

  belongs_to :best_answer, class_name: 'Answer', foreign_key: :best_answer_id, optional: true
  belongs_to :user

  has_many :answers, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :links, as: :linkable, dependent: :destroy
  has_one :reward, class_name: 'Reward', dependent: :destroy

  has_many_attached :files

  validates :title, :body, presence: true

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  scope :less_then_one_day_ago, -> { where('created_at >= ?', Time.zone.yesterday.beginning_of_day) }

  def choose_best_answer(answer, user)
    update!(best_answer: answer)
    return if reward.nil?

    ActiveRecord::Base.transaction do
      reward.update!(user: nil)
      user.rewards << reward
    end
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::ApplicationController
  authorize_resource

  def index
    @questions = Question.all
    render json: @questions
  end

  def show
    @question = Question.find(params[:id])
    render json: @question
  end

  def create
    @question = current_user.questions.build(question_params)
    if @question.save
      render json: @question, status: :created
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      render json: @question, status: :created
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    render json: @question
  end

  private

  def question_params
    params.require(:question).permit(:title, :body,
                                     links_attributes: %i[id name url])
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :question, only: %i[show update destroy]
  before_action :authenticate_user!, except: %i[index show]

  after_action :send_to_channel, only: %i[create]

  authorize_resource

  def index
    @questions = Question.all.order(updated_at: :desc, created_at: :desc)
  end

  def show
    @answer = Answer.new
    @answer.links.build
  end

  def new
    @question = Question.new
    @question.links.build
    @question.build_reward
  end

  def create
    @question = current_user.questions.build(question_params)
    if @question.save
      redirect_to @question, notice: 'Question created successfully'
    else
      render :new
    end
  end

  def update
    @question.update(question_params)
    @questions = Question.all
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: 'question deleted successfully'
  end

  private

  def question
    @question = Question.with_attached_files.find(params[:id])
  end

  def send_to_channel
    return unless @question.persisted?

    QuestionsController.renderer.instance_variable_set(:@env, { 'warden' => warden })
    ActionCable.server.broadcast('questions_channel',
                                 QuestionsController.render(
                                   partial: 'questions/question',
                                   locals: { question: @question,
                                             current_user: nil }
                                 ))
  end

  def question_params
    params.require(:question).permit(:title, :body,
                                     links_attributes: %i[id name url _destroy],
                                     files: [],
                                     reward_attributes: %i[title image])
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/views/questions/_form.slim
p
  = form.label :title
  = form.text_field :title

p
  = form.label :body
  = form.text_area :body

p
  = form.label :files
  = form.file_field :files, multiple: true

  = render 'shared/links_inline_form', form: form

  p Reward
  p
    = form.fields_for :reward do |reward|
      p
        = reward.label :title, 'Reward title'
        = reward.text_area :title

      p
        = reward.label :image
        = reward.file_field :image
= form.submit 'Ask'

app/views/questions/_link_fields.slim
.nested-fields
  .field
    = f.label :name, 'Link name'
    = f.text_field :name
  .field
    = f.label :url
    = f.text_field :url
  = link_to_remove_association "remove link", f

app/views/questions/_question.slim
div id="question-#{question.id}"
  p= question.title
  p= question.body

  = render 'shared/files', resource: question

  = render 'shared/links', resource: question

  = render 'shared/votable', resource: question

  = render 'shared/subscriptable', resource: question

  - if question.id && can?(:update, question)
    p= link_to 'Edit question', '#', class: 'edit-question-link', data: { question_id: question.id}
    p= form_with model: question,
            local: false,
            class: 'hidden',
            html: { id: "form-for-question-#{question.id}" } do |form|
      = render 'questions/form', form: form


  = render 'comments/some_comments', resource: question

app/views/questions/index.slim
.question-errors
  = render 'shared/form_errors', resource: @question

.questions
  = render @questions

- if can?(:create, Question)
  p= link_to 'Ask question', new_question_path

app/views/questions/new.slim
= form_with model: @question do |form|
  = render 'shared/form_errors', resource: @question
  = render 'questions/form', form: form

app/views/questions/show.slim
.question
  p
    = @question.title
  p
    = @question.body

  - if @question.files.attached?
    - @question.files.each do |file|
      p
        = link_to file.filename.to_s, url_for(file)

- if can?(:update, @question)
  = link_to 'Delete',
            question_path(@question),
            method: :delete,
            data: {confirm: 'Are you sure?'}

.links
  = render 'shared/links', resource: @question

.answer-errors
  = render 'shared/form_errors', resource: @answer
= render 'answers/form'

- if @question.reward.present?
  .reward
    p There is a reward for best question
    p= @question.reward.title

.best-answer
  - if @question.best_answer
    = render 'answers/best', best: @question.best_answer

.answers
  = render @question.answers.without_best(@question.best_answer)

app/views/questions/update.js.erb
$('.question-errors').html(`<%= render 'shared/form_errors', resource: @question %>`)

<% if !@question.errors.present? %>
$('.questions').html(`<%= j render @questions %>`)

<% end %>