config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'questions#index'

  resources :questions, except: :edit do
    delete :delete_attachment, on: :member
    resources :answers, shallow: true, only: %i[create destroy edit update] do
      patch :choose_best, on: :member
      delete :delete_attachment, on: :member
    end
  end

  resources :attachments, only: %i[destroy]
  resources :links, only: %i[destroy]
  resources :rewards, only: %i[index]
  resources :votes, only: %i[create destroy]
  resources :comments, only: %i[create new]
  resources :subscriptions, only: %i[create destroy]

  namespace 'api' do
    namespace 'v1' do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, shallow: true, only: %i[index show create update destroy]
      end
    end
  end
end

app/views/shared/_files.slim
- if resource.files.attached?
  - resource.files.each do |file|
    p
      = link_to file.filename.to_s, url_for(file)
      |
      - if can?(:update, resource)
        = link_to 'Remove', attachment_path(file),
                method: :delete,
                data: { confirm: 'Are you sure?' }

app/views/shared/_form_errors.erb
<% if resource.present? && resource.errors.present? %>
    <h2> <%= pluralize(resource.errors.count, 'error') %> detected:</h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li> <%= message %></li>
      <% end %>
    </ul>
<% end %>

app/views/shared/_links.slim
- if resource.links.present?
  p Links:
  ul
    - resource.links.each do |link|
      - if Github::ReadGist.gist_url?(link.url)
        li= link_to 'Link to gist - ' + link.name, link.url
        p= Github::ReadGist.new(link.url).call.description
      - else
        li= link_to link.name, link.url

      - if can?(:update, resource)
        = link_to 'Remove', link_path(link),
                method: :delete,
                data: { confirm: 'Are you sure?' }

app/views/shared/_links_inline_form.slim
p Links:
p
  = form.fields_for :links do |links|
    = render 'link_fields', f: links
  .add-links
    = link_to_add_association 'add link', form, :links

app/views/shared/_navigation.erb
<p class="nav">
  <% if user_signed_in? %>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      <%= current_user.email %>
  <% else %>
      <%= link_to 'Login', new_user_session_path %>
      <%= link_to 'Sign up', new_user_registration_path %>
  <% end %>
  <%= link_to 'to questions', questions_path %>
</p>

app/views/shared/_subscriptable.slim
- if resource.id && can?(:create, Subscription)
  - if resource.subscribed_by?(current_user)
    p= link_to 'stop receiving update news',
            subscription_path(resource.subscription_of(current_user), resource_id: resource.id),
            method: :delete
  - else
    p= link_to 'receive update news',
            subscriptions_path(resource: resource.class, resource_id: resource.id),
            method: :post

app/views/shared/_votable.slim
div class=["voting-panel", resource.id]
  - if resource.id
    .vote-statistic
      p= "#{resource.class} rating"
      p= resource.rating

  - if resource.id && !can?(:update, resource) && can?(:create, Vote)

    -if !resource.voted_by?(current_user)
      div class=["voting"]
        p= link_to 'vote for',
                votes_path(resource: resource.class, resource_id: resource.id, vote_for: true),
                method: :post,
                data: { type: :json},
                remote: true
        p= link_to 'vote against',
                votes_path(resource: resource.class, resource_id: resource.id, vote_for: false),
                method: :post,
                data: { type: :json },
                remote: true
    -else
      .div class=["unvoting"]
        p= link_to 'remove vote',
                vote_path(resource.vote_of(current_user), resource_id: resource.id),
                method: :delete,
                data: { type: :json},
                remote: true,
                class: 'remove-vote'